---
after_deploy:
  - "travis-ci-cloudfront-invalidation -a $AWS_ACCESS_KEY_ID -s $AWS_SECRET_ACCESS_KEY -c $CLOUDFRONT_ID -i '/*' -b $TRAVIS_BRANCH -p $TRAVIS_PULL_REQUEST"
before_deploy:
  - "yarn global add travis-ci-cloudfront-invalidation"
  - "yarn run build"
cache:
  directories:
    - node_modules
  yarn: true
deploy:
  access_key_id: $AWS_ACCESS_KEY_ID
  bucket: $S3_BUCKET
  local-dir: dist
  ? "on"
  :
    branch: master
  provider: s3
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  skip_cleanup: true
language: node_js
node_js:
  - "8"
script:
  - "yarn test"
